name: Workflow to build, test the project.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test packages.
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install depenecies.
        run: make install-root-deps
      - name: Build projects.
        run: |
          make bootstrap-be
          make build-be
          make bootstrap-fe
          make build-fe
      - name: Test projects.
        run: echo "Testing..."
