name: Workflow to build, test the project.
on: [push, pull_request, workflow_dispatch]

jobs:
  build-deploy-fe:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend.
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install depenecies.
        run: yarn
